version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: nxgen
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    depends_on:
      -  mysql

volumes:
  mysql_data:
  grafana_storage: {}

